name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - 1.15
        os:
          - ubuntu-latest

    steps:
      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Install license-header-checker
        run: |
          export GO111MODULE=on
          cd ~
          go get -u github.com/lsm-dev/license-header-checker/cmd/license-header-checker@v1.2.0
          # go get -u mvdan.cc/gofumpt@latest

      - name: Check License Header
        run: |
          license-header-checker -v -a -r -i vendor,license-header-checker,tools ./header/license_header.txt . go
          git status && [[ -z `git status -s` ]]

      - name: gofmt
        run: |
          go fmt ./... && git status && [[ -z `git status -s` ]]
           # gofumpt -l -w . && git status && [[ -z `git status -s` ]]
           # diff -u <(echo -n) <(gofmt -d -s .)

      - name: Test
        run: go test -v ./request -race -coverprofile=coverage.txt -covermode=atomic -v

      - name: Post Coverage
        run: bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}